### ISSUE TITLE
not working for new url same (https://pin.it/2UdwM5n)

### ISSUE THREAD

**Issue by hamaz562006** [elmoiv/pypin#1]
Story videos have recently been added to Pin(multi videos page) and this script not working for this videos
How can I download full page videos?

**Comment by elmoiv** [comment]
It has been 10 months since last time I checked this repo.
I will try to fix this bug after my exams.

I also encourage contributing with fixes if you wish :)

**Comment by elmoiv** [comment]
The URL in the title redirects to this error page: https://www.pinterest.com/?show_error=true

Could you please send a working URL?

**Comment by hamaz562006** [comment]
> The URL in the title redirects to this error page: https://www.pinterest.com/?show_error=true
> 
> Could you please send a working URL?

log in to pin

**Comment by elmoiv** [comment]
This script scrapes public content only :)

Please provide an accessible public URL with the "multi video" thing in order to identify the issue.
