### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by hamaz562006** [elmoiv/pypin#2]
don't work please fix

**Comment by elmoiv** [comment]
please provide a good explanation of your issue with a reproduction of the bug you've faced.

**Comment by hamaz562006** [comment]
> please provide a good explanation of your issue with a reproduction of the bug you've faced.

Traceback (most recent call last):
  File "D:\000209\Downloads\pypin-main\pypin-main\pypin.py", line 19, in <module>
    TYPE, MEDIA_URL    =      decideType(JSON)
  File "D:\000209\Downloads\pypin-main\pypin-main\tools.py", line 30, in decideType
    response = jsonData['resourceResponses'][0]['response']
KeyError: 'resourceResponses'


Not available with new changes to Pinterest Json ['resourceResponses'] [0] ['response']

**Comment by elmoiv** [comment]
Thanks. I will try to fix it ASAP :)

**Comment by elmoiv** [comment]
Fixed JSON fetching.
Use v1.0 from here:
https://github.com/elmoiv/pypin/releases/tag/1.0
