### ISSUE TITLE
Error in getJson (), the regex does not find the json pattern in scriptag

### ISSUE THREAD

**Issue by fr4nkastro** [elmoiv/pypin#3]
```
File "C:\Users\frank\Documents\Allan\Tools\pypin\pypin.py", line 18, in <module>
    JSON               =      getJson(HTML)
  File "C:\Users\frank\Documents\Allan\Tools\pypin\tools.py", line 18, in getJson
    return json.loads(re.findall(r'>(.*)<', str(scriptTag))[0])
IndexError: list index out of range
```

**Comment by elmoiv** [comment]
Fixed JSON fetching.
Use v1.0 from here:
https://github.com/elmoiv/pypin/releases/tag/1.0

**Comment by fr4nkastro** [comment]
With the format that you show it works fine, but why is it not compatible with the pins that have a longer format pin?
```
https://www.pinterest.com/pin/AaQ7158KxwC_0Z2gtSsuHFPk6SDEyNwWnmkian5bXFIBsAdJYxuyoe4/
```

**Comment by elmoiv** [comment]
Added support for different Pinterest URL formats
Use v1.1 from here:
https://github.com/elmoiv/pypin/releases/tag/1.1

If you have any ideas or enhancement for pypin, feel free to contribute with a pull request

**Comment by fr4nkastro** [comment]
Maybe turn the tool into a board downloader . It' looks that I have a lot to learn in python... Do you think that implement a crawler from a board link can help to do It?

**Comment by elmoiv** [comment]
The aim of this script is to be as minimal as possible.
I think there are many projects out there that can handle boards and has tons of features.

For now, pypin is for quick use cases
